# NUMPY

In [1]:
import numpy as np

In [2]:
# pkg.__version__  => to check package version
np.__version__

'1.21.0'

In [3]:
my_list = [0,1,2,3,4,5]
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5]
<class 'list'>


In [4]:
# array
arr1 = np.array(my_list)
arr1

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(3.0)

array([0., 1., 2.])

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(10,20)  # first  argument is less than second argument

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [10]:
np.arange(10,10)

array([], dtype=int32)

In [11]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [12]:
np.arange(0,30,8)

array([ 0,  8, 16, 24])

In [13]:
np.zeros(3) #  system give us is called parameter tunning

array([0., 0., 0.])

In [14]:
np.zeros(3,dtype = int)

array([0, 0, 0])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
n1 = (6,7)
n2=(6,8)
print(np.zeros(n1))
print()
print(np.zeros(n2))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(np.zeros(n2,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [18]:
np.ones(n1,dtype = int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [19]:
np.random.rand(2,4)

array([[0.40497527, 0.7347251 , 0.61911126, 0.53129669],
       [0.0577495 , 0.15027262, 0.85880148, 0.71909922]])

In [20]:
np.random.randint(1,10)

3

In [21]:
np.random.randint(0,5)

3

In [22]:
np.random.randint(10,20,3)

array([19, 19, 14])

In [23]:
np.random.randint(10,30,10)

array([24, 26, 23, 20, 24, 15, 20, 25, 15, 10])

In [24]:
np.random.randint(10,40,(5,5)) # multi dimension array

array([[36, 19, 39, 13, 34],
       [25, 33, 13, 28, 24],
       [15, 27, 12, 22, 10],
       [35, 13, 28, 31, 12],
       [26, 39, 25, 32, 20]])

In [25]:
np.arange(1,13).reshape(3,4)   

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 12, 13, 10],
       [13, 12, 18, 16],
       [14, 17, 11, 14],
       [14, 18, 13, 17],
       [17, 15, 15, 11]])

In [27]:
type(b)

numpy.ndarray

In [28]:
# slicing, indexing in numpy
b[:]

array([[14, 12, 13, 10],
       [13, 12, 18, 16],
       [14, 17, 11, 14],
       [14, 18, 13, 17],
       [17, 15, 15, 11]])

In [29]:
b[1:3]

array([[13, 12, 18, 16],
       [14, 17, 11, 14]])

In [30]:
b[1,2]

18

In [31]:
b[3,2]

13

In [32]:
a=np.random.randint(10,20,(5,4))

In [33]:
a

array([[12, 15, 11, 18],
       [15, 17, 16, 18],
       [13, 13, 16, 14],
       [18, 15, 12, 14],
       [16, 19, 19, 15]])

In [34]:
a[-4:2]

array([[15, 17, 16, 18]])

# operations

In [35]:
x = np.random.randint(10,20,10)
x

array([16, 14, 11, 18, 13, 11, 17, 19, 19, 15])

In [36]:
id(x)

2670332419888

In [37]:
arr1 =np.random.randint(1,100,(10,10))
arr1

array([[87, 79, 27, 23, 50, 10, 32, 10, 14, 35],
       [26, 89, 83, 37, 55, 89, 11, 22, 61, 48],
       [69, 81, 72, 36,  6, 38, 42, 99, 90, 34],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38],
       [43, 43, 10, 57, 29, 37, 64, 66, 56, 33],
       [65, 34, 68, 53, 81, 78, 96, 78,  4, 79],
       [49, 66, 78, 69, 38, 47, 17, 61, 27, 29],
       [ 7, 86, 56, 56, 62, 43, 61, 72, 86, 30],
       [91, 50, 40, 62,  3,  8, 57,  7,  7, 83],
       [83, 11, 21, 13, 83, 58, 75, 87, 20, 56]])

In [38]:
arr1[:4]

array([[87, 79, 27, 23, 50, 10, 32, 10, 14, 35],
       [26, 89, 83, 37, 55, 89, 11, 22, 61, 48],
       [69, 81, 72, 36,  6, 38, 42, 99, 90, 34],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38]])

In [39]:
arr1[-5:-2]

array([[65, 34, 68, 53, 81, 78, 96, 78,  4, 79],
       [49, 66, 78, 69, 38, 47, 17, 61, 27, 29],
       [ 7, 86, 56, 56, 62, 43, 61, 72, 86, 30]])

In [40]:
arr1[2:4]

array([[69, 81, 72, 36,  6, 38, 42, 99, 90, 34],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38]])

In [41]:
arr1

array([[87, 79, 27, 23, 50, 10, 32, 10, 14, 35],
       [26, 89, 83, 37, 55, 89, 11, 22, 61, 48],
       [69, 81, 72, 36,  6, 38, 42, 99, 90, 34],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38],
       [43, 43, 10, 57, 29, 37, 64, 66, 56, 33],
       [65, 34, 68, 53, 81, 78, 96, 78,  4, 79],
       [49, 66, 78, 69, 38, 47, 17, 61, 27, 29],
       [ 7, 86, 56, 56, 62, 43, 61, 72, 86, 30],
       [91, 50, 40, 62,  3,  8, 57,  7,  7, 83],
       [83, 11, 21, 13, 83, 58, 75, 87, 20, 56]])

In [42]:
arr1[:-3]

array([[87, 79, 27, 23, 50, 10, 32, 10, 14, 35],
       [26, 89, 83, 37, 55, 89, 11, 22, 61, 48],
       [69, 81, 72, 36,  6, 38, 42, 99, 90, 34],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38],
       [43, 43, 10, 57, 29, 37, 64, 66, 56, 33],
       [65, 34, 68, 53, 81, 78, 96, 78,  4, 79],
       [49, 66, 78, 69, 38, 47, 17, 61, 27, 29]])

In [43]:
arr1[::-3]

array([[83, 11, 21, 13, 83, 58, 75, 87, 20, 56],
       [49, 66, 78, 69, 38, 47, 17, 61, 27, 29],
       [40, 71,  4, 76,  3, 50, 34, 90, 70, 38],
       [87, 79, 27, 23, 50, 10, 32, 10, 14, 35]])

In [44]:
arr1.max()

99

In [45]:
arr1.mean()

49.6

In [46]:
# 
from numpy import *
a = (1,2,3,4,5,6)


In [47]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
mat[4,4]

44

In [49]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
col = 6

In [51]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [52]:
# coloum [:,col]
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [53]:
# entire row
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [54]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat[2:6,2:]

array([[22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59]])

In [56]:
# masking
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
id(mat)

2670332552752

In [58]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [59]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [60]:
mat[mat!=50] # skip the value

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])